
# cargo-vet audits file

[[audits.aho-corasick]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
version = "1.1.4"

[[audits.anyhow]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.0.100 -> 1.0.103"

[[audits.arrayvec]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.7.7 -> 0.7.8"

[[audits.cargo-platform]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.1.3 -> 0.3.0"

[[audits.cargo_metadata]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.20.0 -> 0.23.1"

[[audits.dylint_internal]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
version = "6.0.1"

[[audits.dylint_linting]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
version = "6.0.1"

[[audits.log]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.29 -> 0.4.33"

[[audits.paste]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
version = "1.0.15"

[[audits.regex]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
version = "1.12.4"

[[audits.regex-automata]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
version = "0.4.14"

[[audits.regex-syntax]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.8.5 -> 0.8.11"

[[audits.semver]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.0.26 -> 1.0.28"

[[audits.serde_spanned]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.0.4 -> 1.1.1"

[[audits.toml]]
who = "Lewis <priorlewis43@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.7.4 -> 1.1.2+spec-1.1.0"
